# Generated by Django 4.1.1 on 2022-10-06 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JsonAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_album', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JsonUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address_city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JsonPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_post', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=500)),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapp.jsonuser')),
            ],
        ),
        migrations.CreateModel(
            name='JsonPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_photo', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('thumbnail_url', models.URLField()),
                ('id_albums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapp.jsonalbum')),
            ],
        ),
        migrations.CreateModel(
            name='JsonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comment', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=500)),
                ('id_posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapp.jsonpost')),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapp.jsonuser')),
            ],
        ),
        migrations.AddField(
            model_name='jsonalbum',
            name='id_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapp.jsonuser'),
        ),
    ]
