# Generated by Django 4.1.2 on 2022-10-05 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JsonUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address_city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JsonAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_album', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapp.jsonuser')),
            ],
        ),
    ]
