# Generated by Django 4.1.1 on 2022-10-06 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_photo', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('thumbnail_url', models.URLField()),
                ('id_albums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapp.jsonalbum')),
            ],
        ),
    ]
